services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: tracker-sales-api
    env_file: .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - dokploy-network
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: tracker-sales-ui
    restart: unless-stopped
    networks:
      - dokploy-network
      - default

  nginx:
    image: nginx:alpine
    container_name: tracker-sales-nginx
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    labels:
      - traefik.docker.network=dokploy-network
      - traefik.http.routers.tracker-sales-os-trackersalesos-qfvalh-11-web.rule=Host(`trackersales.trackergps.cloud`)
      - traefik.http.routers.tracker-sales-os-trackersalesos-qfvalh-11-web.entrypoints=web
      - traefik.http.services.tracker-sales-os-trackersalesos-qfvalh-11-web.loadbalancer.server.port=80
      - traefik.http.routers.tracker-sales-os-trackersalesos-qfvalh-11-web.service=tracker-sales-os-trackersalesos-qfvalh-11-web
      - traefik.http.routers.tracker-sales-os-trackersalesos-qfvalh-11-web.middlewares=redirect-to-https@file
      - traefik.http.routers.tracker-sales-os-trackersalesos-qfvalh-11-websecure.rule=Host(`trackersales.trackergps.cloud`)
      - traefik.http.routers.tracker-sales-os-trackersalesos-qfvalh-11-websecure.entrypoints=websecure
      - traefik.http.services.tracker-sales-os-trackersalesos-qfvalh-11-websecure.loadbalancer.server.port=80
      - traefik.http.routers.tracker-sales-os-trackersalesos-qfvalh-11-websecure.service=tracker-sales-os-trackersalesos-qfvalh-11-websecure
      - traefik.http.routers.tracker-sales-os-trackersalesos-qfvalh-11-websecure.tls.certresolver=letsencrypt
      - traefik.enable=true
    networks:
      - dokploy-network
      - default

networks:
  default:
    name: tracker-sales-network
  dokploy-network:
    external: true
